version: '3'
services:
#mssql docker
  fitnesscentar-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
        - 1433
    networks:
      - fitnesscentar-net

  fitnesscentar-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=fitnessCentar-sql,1433;Database=210420;User=sa;Password=QWElkj132!;ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 7150:7150
    networks:
      - fitnesscentar-net
    links:
      - fitnesscentar-sql
    depends_on:
      - fitnesscentar-sql
      
networks:
  fitnesscentar-net:
    driver: bridge      