version: '3'
services:
  fitnesscentar-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - fitnesscentar-net

  rabbitmq:
    image: rabbitmq:3.12.1-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
    networks:
      - fitnesscentar-net

  fitnesscentar-notifications:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.notifications
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=mypass
      - RABBITMQ_VIRTUALHOST=/
    depends_on:
      - rabbitmq
      - fitnesscentar-sql
      - fitnesscentar-api
    networks:
      - fitnesscentar-net
    ports:
      - 7111:80

  fitnesscentar-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=fitnesscentar-sql,1433;Database=210420;User=sa;Password=QWElkj132!;ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=mypass
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - 7150:7150
    networks:
      - fitnesscentar-net
    depends_on:
      - fitnesscentar-sql

networks:
  fitnesscentar-net:
    driver: bridge